name: Base FastAPI image
on: 
  push:
    paths:
      - 'base_fastapi/**'  # Specify path to your directory

jobs:
  build-and-push-fastapi-image:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      

      - name: Build and Push
        run: |
          cd base_fastapi/
          chmod +x build.sh  # Ensure the script is executable
          ./build.sh