name: Arm64 CPU edge node image build and push
on: 
  push:
    paths:
      - 'base_edge_node_arm64_cpu/**'  # Specify path to your directory

jobs:
  build-and-push-edge-node-image:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "aixpand/aixpbuilder"

      - name: Cleanup space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          docker system prune -af

      - name: Build and push CPU
        uses: docker/build-push-action@v5
        with:
          context: ./base_edge_node_arm64_cpu
          file: ./base_edge_node_arm64_cpu/Dockerfile
          push: true
          tags: "aidamian/base_edge_node_arm64_cpu:latest"
          platforms: linux/arm64
